language: python
cache: pip

branches:
  only:
    - v3

notifications:
  email:
    on_success: change
    on_failure: always

python:
  - "3.7"
  - "3.8"
install:
  - pip install black==19.10b0
script:
  - python -m compileall .
  - black --check -l 120 `git ls-files "*.py"`
